# render.yaml
services:
  - type: web
    name: finance-tracker-backend
    runtime: node
    rootDir: backend
    buildCommand: cd backend && npm install
    startCommand: node backend/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        fromGroup: finance-tracker-secrets
      - key: JWT_SECRET
        fromGroup: finance-tracker-secrets


         # Frontend
  - type: web
    name: finance-tracker-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://finance-tracker-backend.onrender.com/api